[tool.black]
line-length = 79
skip-string-normalization = true
extend-exclude = '^.*/migrations/.*$'

[tool.isort]
extend_skip_glob = ['*/migrations/*']
skip_gitignore = true
profile = 'black'
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79

[tool.mypy]
no_strict_optional = true
ignore_missing_imports = true
check_untyped_defs = true
exclude = ['^.*/\.venv/*', '^.*/migrations/*']

[tool.pytest.ini_options]
testpaths = ['tests']
